- title: Intro to Physical Security
  hosts:
      - name: Joey
      - name: Abigail
  start: 2026-01-22T17:30:00-5:00
  end: 2026-01-22T18:30:00-5:00
  location: CYB-2780
  group: physical security

